### ISSUE TITLE
When i download newest source, it doesn't build. display error

### ISSUE THREAD

**Issue by dennislee01** [chanil1218/elasticsearch-analysis-korean#2]
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-analysis-korean 1.3.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-analysis-korean ---
[INFO] 
[INFO] --- maven-jflex-plugin:1.4.3-r1:generate (default) @ elasticsearch-analysis-korean ---
[INFO]   generated D:\elasticsearch-analysis-korean\src\main\java\org\apache\lucene\analysis\kr\KoreanTokenizerImpl.java
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ elasticsearch-analysis-korean ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 14 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ elasticsearch-analysis-korean ---
[INFO] Compiling 49 source files to D:\elasticsearch-analysis-korean\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[11,7] cannot find symbol
symbol  : constructor TokenFilterFactory()
location: class org.apache.lucene.analysis.util.TokenFilterFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[22,10] cannot find symbol
symbol  : method init(java.util.Map<java.lang.String,java.lang.String>)
location: class org.apache.lucene.analysis.util.TokenFilterFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[23,19] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[24,17] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[25,18] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[26,16] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[11,7] org.apache.solr.analysis.kr.KoreanTokenizerFactory is not abstract and does not override abstract method create(org.apache.lucene.util.AttributeSource.AttributeFactory,java.io.Reader) in org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[15,33] cannot find symbol
symbol  : constructor TokenizerFactory()
location: class org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[19,42] cannot find symbol
symbol  : constructor TokenizerFactory()
location: class org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[23,18] create(java.io.Reader) in org.apache.solr.analysis.kr.KoreanTokenizerFactory cannot override create(java.io.Reader) in org.apache.lucene.analysis.util.TokenizerFactory; overridden method is final
[INFO] 10 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.232s
[INFO] Finished at: Tue Jun 18 22:24:13 KST 2013
[INFO] Final Memory: 15M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-korean: Compilation failure: Compilation failure:
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[11,7] cannot find symbol
[ERROR] symbol  : constructor TokenFilterFactory()
[ERROR] location: class org.apache.lucene.analysis.util.TokenFilterFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[22,10] cannot find symbol
[ERROR] symbol  : method init(java.util.Map<java.lang.String,java.lang.String>)
[ERROR] location: class org.apache.lucene.analysis.util.TokenFilterFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[23,19] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[24,17] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[25,18] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanFilterFactory.java:[26,16] getBoolean(java.util.Map<java.lang.String,java.lang.String>,java.lang.String,boolean) in org.apache.lucene.analysis.util.AbstractAnalysisFactory cannot be applied to (java.lang.String,boolean)
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[11,7] org.apache.solr.analysis.kr.KoreanTokenizerFactory is not abstract and does not override abstract method create(org.apache.lucene.util.AttributeSource.AttributeFactory,java.io.Reader) in org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[15,33] cannot find symbol
[ERROR] symbol  : constructor TokenizerFactory()
[ERROR] location: class org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[19,42] cannot find symbol
[ERROR] symbol  : constructor TokenizerFactory()
[ERROR] location: class org.apache.lucene.analysis.util.TokenizerFactory
[ERROR] \elasticsearch-analysis-korean\src\main\java\org\apache\solr\analysis\kr\KoreanTokenizerFactory.java:[23,18] create(java.io.Reader) in org.apache.solr.analysis.kr.KoreanTokenizerFactory cannot override create(java.io.Reader) in org.apache.lucene.analysis.util.TokenizerFactory; overridden method is final
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by chanil1218** [comment]
안녕하세요, 이슈 올려 주셔서 감사합니다!
[위 문제](http://sourceforge.net/p/jflex/bugs/122/)는 저도 발견해서 jflex에 리포트 하였는데, 
아직 수정이 안된 것 같습니다. 
임시로는 생성된 java 파일의 UTF-8로 인코딩이 깨진 부분을 제거하면 되는데, 
해결할 수 있는 문제인지 한번 알아보겠습니다!

**Comment by dennislee01** [comment]
올려주신 0.90.1버전용 형태소 jar로 설치해서는 잘작동하는듯합니다.
그건 문제가 없는것인지요? ㅎㅎ 저도 도와드리고 싶은데. 좋은 내용 공개해주셔서 감사할 따름입니다.

**Comment by chanil1218** [comment]
우선은 jflex 버그픽스 기다려보고, 연락 없으면 패치해서 Pull request 보내볼게요!
